Fix WindowBuilder 1.9.8 fails to run with IBM Semeru Java 17
Running WindowBuilder 1.9.8 with the "IBM Semeru Runtime Open Edition
17.0.3.0 (build 17.0.3+7)" Java 17 VM on Windows 10 (which can be
download from <https://developer.ibm.com/semeru-runtime-downloads/>)
causes a NPE, when e.g. invoking "File > New > Other...: WindowBuilder >
Swing Designer > Application Window":
------------------------------------------------------------------------
org.osgi.framework.BundleException: Error starting module.
osgi.identity; osgi.identity="org.eclipse.wb.core.java";
type="osgi.bundle"; version:Version="1.9.2.202203170939";
singleton:="true" [id=465]
    ...
Caused by: java.lang.NullPointerException
	at java.base/java.lang.Class.getModule(Class.java)
	at java.base/sun.invoke.util.VerifyAccess.isClassAccessible(VerifyAccess.java:227)
	at java.base/java.lang.invoke.MethodHandles$Lookup.isClassAccessible(MethodHandles.java:3703)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(MethodHandles.java:3691)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3652)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2594)
	at io.github.toolfactory.jvm.function.catalog.PrivateLookupInMethodHandleSupplier$ForJava9.<init>(PrivateLookupInMethodHandleSupplier.java:69)
	... 184 more
------------------------------------------------------------------------

Updating the following dependencies to their latest versions from Maven
Central fixes the issue:
- org.burningwave:core - from 12.4.0 to 12.53.0
- org.burningwave:jvm-driver - from 6.0.0 to 8.6.0
- io.github.toolfactory:jvm-driver - from 8.0.0 to 9.1.1