Raise lower bound of SWT bundle to 3.126
The PropertyTable class calls the method FigureCanvas.setScrollbarsMode
which has been introduced with the given version. Trying to use the
editor with an older version otherwise leads to a NoSuchMethodError.

The bound is set implicitly via org.eclipse.ui, which re-exports the SWT
bundle.

Amends e6c43ce3c25e2a893acf2e90e04dd0ba68402c7b