Use `ColorConstants.black` in ElPropertyUiConfiguration
The class might be loaded outside the SWT UI thread, in which case
`PlatformUI.getWorkbench()` returns `null` and thus leading to a
`NoClassDefFoundError`.