Use Require-Bundle header for Draw2D/GEF to specifiy lower bounds
The packages exported by GEF are unversioned. It is therefore not
possible to set the version with which WindowBuilder is compatible. The
result of this are NoSuchMethodErrors and similar problems.

https://github.com/eclipse-windowbuilder/windowbuilder/issues/760