Fix: NoClassDefFoundError in MVEL when using Java 21
MVEL is internally referencing java.lang.Compiler, which has been
removed with Java 21: https://bugs.openjdk.org/browse/JDK-8205129

Update MVEL from 2.4.15 to 2.5.0, where this issue has been resolved.
See #579